name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace Watchlist.xcworkspace -scheme Watchlist -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator'
    - name: Test
      run: xcodebuild -workspace Watchlist.xcworkspace -scheme Watchlist -sdk iphonesimulator -destination 'platform=iOS Simulator' test
